config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'


  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member
    resources :food_recipes, only: [:new, :create, :edit, :update, :destroy]
  end
  
  
  get '/public', to: 'recipes#new'
  resources :inventories, only: [:index, :show, :new, :edit,  :update, :create, :destroy]

  # Route for the 'General shopping list' page handled by FoodRecipesController
  get '/general_shopping_list', to: 'general_shopping_list#shopping_list', as: 'general_shopping_list'

  
end

app/models/inventory.rb
class Inventory < ApplicationRecord
  validates :food, presence: true

  belongs_to :user
  belongs_to :food
  belongs_to :recipe
end

app/controllers/inventories_controller.rb
class InventoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @inventories = current_user.inventories
    @total_price = 0

    @inventories.each do |inventory|
      food = Food.find(inventory.food_id)
      @total_price += (food.price || 0) * (inventory.quantity || 0)
    end
  end

  def show
    @inventories = Inventory.all # Replace with the appropriate query to retrieve your inventory data
  end

  def new
    @inventory = Inventory.new
  end

  def edit
    @inventory = Inventory.find(params[:id])
  end

  def create
    @inventory = current_user.inventories.build(inventory_params)
    if @inventory.save
      redirect_to inventories_path, notice: 'Food added to inventory.'
    else
      render :new
    end
  end

  def destroy
    @inventory = Inventory.find(params[:id])
    @inventory.destroy
    redirect_to inventories_path, notice: 'Food removed from inventory.'
  end

  private

  def inventory_params
    params.require(:inventory).permit(:food_id, :quantity, :description)
  end
end

app/helpers/inventories_helper.rb
module InventoriesHelper
end

app/views/inventories/_show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.food.name %></td>
        <td><%= inventory.quantity %> <%= inventory.food.measurement_unit %></td>
        <td>
          <%= link_to 'Modify', edit_inventory_path(inventory), class: 'btn btn-primary' %>
        </td>
        <td>
          <%= form_with(model: inventory, local: false, html: { method: :delete, data: { confirm: 'Are you sure?' } }) do |form| %>
            <%= form.submit 'Remove', class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/inventories/index.html.erb
<h1>Inventory</h1>

<div class="row">
  <% @inventories.each do |inventory| %>
    <div class="col-md-9 mb-4">
      <div class="card">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <h5 class="card-title"><%= link_to inventory.food.name, inventory_path(inventory) %></h5>
            <p class="card-text"><%= inventory.description %></p>
          </div>
        </div>
        <div class="card-footer">
          <%= form_with(model: inventory, local: false, html: { method: :delete, data: { confirm: 'Are you sure?' } }) do |form| %>
            <%= form.submit 'Remove', class: 'btn btn-danger' %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'Add food', new_inventory_path, class: 'btn btn-primary' %>

app/views/inventories/new.html.erb
<h1>Add Food to Inventory</h1>

<%= form_for @inventory do |f| %>
  <div>
    <%= f.label :food_id, "Select Food" %>
    <%= f.collection_select :food_id, Food.all, :id, :name %>
  </div>
  <div>
    <%= f.label :description, "description" %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.label :quantity, "Quantity" %>
    <%= f.number_field :quantity %>
  </div>
  <%= f.submit "Add to Inventory" %>
<% end %>

app/views/inventories/show.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @inventories.each do |inventory| %>
      <tr>
        <td><%= inventory.food.name %></td>
        <td><%= inventory.quantity %> <%= inventory.food.measurement_unit %></td>
        <td>
          <%= form_with(model: inventory, local: false, html: { method: :delete, data: { confirm: 'Are you sure?' } }) do |form| %>
            <%= form.submit 'Remove', class: 'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>