config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'


  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member
    resources :food_recipes, only: [:new, :create, :edit, :update, :destroy]
  end
  
  
  get '/public', to: 'recipes#new'
  resources :inventories, only: [:index, :show, :new, :edit,  :update, :create, :destroy]

  # Route for the 'General shopping list' page handled by FoodRecipesController
  get '/general_shopping_list', to: 'general_shopping_list#shopping_list', as: 'general_shopping_list'

  
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def self.ispublic
    where(is_public: true).order(created_at: :desc)
  end
  belongs_to :user
  has_many :inventories
  has_and_belongs_to_many :foods, join_table: 'recipe_foods'
  has_many :food_recipes, dependent: :destroy

  # Validations.
  validates :name, :description, presence: true
  validates :name, length: { maximum: 250 }
  validates :preparation_time, :cooking_time, presence: true, comparison: { greater_than_or_equal_to: 0 },
                                              numericality: { only_integer: true }
  validates :public, inclusion: { in: [true, false] }

  def total_price
    food_recipes.includes(:food).sum { |food_recipe| food_recipe.food.price * food_recipe.quantity }
  end

  def count_ingredients
    foods.count
  end

  def convert_hours_to_minutes
    self.preparation_time = (preparation_time.to_f * 60).to_i
    self.cooking_time = (cooking_time.to_f * 60).to_i
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  #     # Devise for authentication
  before_action :authenticate_user!

  def index
    @recipes = current_user.recipes
    @missing_ingredients = {}

    @recipes.each do |recipe|
      missing_for_this_recipe = []

      recipe.food_recipes.each do |food_recipe|
        missing_for_this_recipe << food_recipe.food unless current_user.foods.include?(food_recipe.food)
      end

      @missing_ingredients[recipe.id] = missing_for_this_recipe unless missing_for_this_recipe.empty?
    end
  end

  def show
    @recipe = Recipe.includes(:food_recipes).find(params[:id])
    @inventories = current_user.inventories
    # @recipe = Recipe.find(params[:id])
    # rescue ActiveRecord::RecordNotFound
    # redirect_to recipes_path, alert: 'Recipe not found.'
  rescue ActiveRecord::RecordNotFound
    redirect_to recipes_path, alert: 'Recipe not found.'
    @inventories = current_user.inventories
  end

  def update_status
    @recipe = Recipe.find(params[:id])
    if @recipe.update(public: params[:public])
      render json: { status: 'success' }
    else
      render json: { status: 'error', message: @recipe.errors.full_messages.join(', ') }, status: 400
    end
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)

    if @recipe.save
      redirect_to recipes_path, Notice: 'Recipes added successfully'
    else
      flash[:notice] = @recipe.errors.full_messages.join(', ')
      redirect_to request.referrer
    end
  end

  def public_recipes
    @recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if @recipe.destroy
      flash[:success] = 'Recipe removed successfully.'
    else
      flash[:error] = 'Error removing the recipe.'
    end
    redirect_to recipes_path
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/index.html.erb
<div class="container">
  <h1 class="mt-4">My Recipes</h1>

  <ul class="list-group mt-3">
    <% @recipes.each do |recipe| %>
      <li class="list-group-item">
        <div class="d-flex justify-content-between align-items-center">
          <span>
            <%= link_to recipe.name, recipe_path(recipe) %>
            <p class="mt-2"><%= recipe.description %></p>
          </span>
          <% if @missing_ingredients[recipe.id] %>
            <div class="d-flex">
              <div class="missing-ingredients">
                <p class="mb-1">Missing Ingredients:</p>
                <ul>
                  <% @missing_ingredients[recipe.id].each do |ingredient| %>
                    <li><%= ingredient.name %></li>
                  <% end %>
                </ul>
              </div>
              <%= form_with(model: recipe, local: false, html: { method: :delete, data: { confirm: 'Are you sure?' }, class: 'ml-3' }) do |form| %>
                <%= form.submit 'Remove', class: 'btn btn-danger' %>
              <% end %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
</div>

app/views/recipes/new.html.erb
<%= image_tag '', class: 'headline-image w-100 opacity-6' %>
<section class="main_page_wrapper w-100">
  <div class="container section-container">
    <div class="row d-flex flex-column align-items-center">

      <h1 class="main-title">Create a new Recipe</h1>

      <div class="form-wrapper">
        <%= form_with(model: @recipe, url: recipes_path, html: { class: 'form' }) do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, required: true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label 'Preparation time (hours):' %>
            <%= f.number_field :preparation_time, min: 0, step: 0.01, required: true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label 'Cooking time (hours):' %>
            <%= f.number_field :cooking_time, min: 0, step: 0.01, required: true, class: 'form-control' %>
          </div>
          <div class="form-group">
            <div class="d-flex flex-row">
              <%= f.radio_button :public, true, class: 'form-check-input' %>
              <%= f.label 'Public', class: 'form-check-label' %>
            </div>
            <div class="d-flex flex-row">
              <%= f.radio_button :public, false, class: 'form-check-input' %>
              <%= f.label 'Private', class: 'form-check-label' %>
            </div>
          </div>
          <div class="form-group" id="recipe-description">
            <%= f.label :description %>
            <%= f.text_area :description, required: true, class: 'form-control' %>
          </div>
          <div class="actions w-100 d-flex flex-row justify-end align-items-center">
            <%= f.submit "Save recipe", class: 'btn btn-primary' %>
            <%= link_to 'Cancel', recipes_path, class: 'btn btn-warning' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/recipes/show.html.erb
<div class="container">
  <h1 class="display-4 recipe-name"><%= @recipe.name %></h1>

  <div class="row">
    <div class="col-md-6">
      <h2 class="h4 preparation-time">Preparation Time: <%= @recipe.preparation_time %></h2>
      <h2 class="h4 cooking-time">Cooking Time: <%= @recipe.cooking_time %></h2>
    </div>

    <%# Toggle button for public/private %>
    <div class="col-md-6">
      <% if can? :manage, @recipe %>
        <div class="toggle-container">
          <%= turbo_frame_tag "Public" do %>
            <button class="toggle-button <%= 'is-public' if @recipe.public %>" id="toggleButton">
              <span class="toggle-label">Public</span>
              <div class="toggle-switch">
                <div class="toggle-handle"></div>
              </div>
            </button>
          <% end %>
        </div>
      <% end %>
    </div>

    <h2 class="h4 description">Description:</h2>
    <p><%= @recipe.description %></p>

    <div class="row justify-content-between">
      <div class="col-md-6 mb-3">
        <%= link_to 'Generate shopping list', general_shopping_list_path, class: 'btn btn-primary btn-block generate-shopping-button', id: 'generateShoppingButton' %>
      </div>
      <div class="col-md-6">
        <% if can? :manage, @recipe %>
          <%= link_to 'Add Ingredient', foods_path, class: 'btn btn-secondary btn-block add-ingredient-button' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

  <div class="inventory-section">
    <%= render 'inventories/show' %>
  </div>

<!-- Inventory Modal -->
<div id="inventoryModal" class="modal">
  <div class="modal-content">
  <span id="closeInventoryButton" style="float:right; cursor:pointer;">&times;</span>
    <h2>Generating Shopping List</h2>
    <h3>Choose an inventory to use</h3>
    <select id="inventoryDropdown">
     <% @inventories.each do |inventory| %>
    <option value="<%= inventory.id %>"><%= inventory.food.name %></option>
  <% end %>
    </select>
    <button id="generateInventoryButton"><%= link_to "Generate Shopping List", general_shopping_list_path, class: "btn btn-primary" %></button>
  </div>
</div>



<script>
  document.addEventListener('DOMContentLoaded', function() {
  const generateShoppingButton = document.getElementById('generateShoppingButton');
  const inventoryModal = document.getElementById('inventoryModal');
  const generateInventoryButton = document.getElementById('generateInventoryButton');
  const closeInventoryButton = document.getElementById('closeInventoryButton');
  const inventoryDropdown = document.getElementById('inventoryDropdown');

  // Handle the "Generate Shopping List" button click
  generateShoppingButton.addEventListener('click', function(event) {
    event.preventDefault(); // Prevent the default link behavior
    inventoryModal.style.display = 'block';
  });

  // Handle the "Close" button click
  closeInventoryButton.addEventListener('click', function(event) {
    event.preventDefault();
    inventoryModal.style.display = 'none';
  });

  // Handle the "Generate" button click
  generateInventoryButton.addEventListener('click', function(event) {
      event.preventDefault();
  
      // Get the selected inventory value from the dropdown
      const selectedInventory = inventoryDropdown.value;
      const recipeId = "<%= @recipe.id %>"; // Assuming this is the current recipe's ID
  
      // Construct the URL for the shopping list page with the selected inventory and recipe
      const shoppingListURL = `/general_shopping_list?inventory_id=${selectedInventory}&recipe_id=${recipeId}`;
  
      // Redirect to the shopping list page
      window.location.href = shoppingListURL;
  });
});

document.addEventListener('DOMContentLoaded', function() {
    const toggleButton = document.getElementById('toggleButton');

    // Obtener el estado inicial basado en la clase del botón
    let isPublic = toggleButton.classList.contains('is-public');

    // Function to update the button's state and class
    const updateToggleButton = () => {
      toggleButton.classList.toggle('is-public'); // Add or remove the 'is-public' class
    };

    // Add a click event listener to the button
    toggleButton.addEventListener('click', function() {
      // Send an AJAX request to update the recipe's status
      fetch("<%= update_status_recipe_path(@recipe) %>", {
        method: "PATCH",
        headers: {
          "Content-Type": "application/json",
          "X-CSRF-Token": "<%= form_authenticity_token %>",
        },
        body: JSON.stringify({ public: !isPublic }),
      })
      .then((response) => {
        if (response.ok) {
          isPublic = !isPublic; // Toggle the state
          updateToggleButton();
        } else {
          console.error("Failed to update recipe status");
        }
      })
      .catch((error) => {
        console.error("Error:", error);
      });
    });
});




</script>