config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'


  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member
    resources :food_recipes, only: [:new, :create, :edit, :update, :destroy]
  end
  
  
  get '/public', to: 'recipes#new'
  resources :inventories, only: [:index, :show, :new, :edit,  :update, :create, :destroy]

  # Route for the 'General shopping list' page handled by FoodRecipesController
  get '/general_shopping_list', to: 'general_shopping_list#shopping_list', as: 'general_shopping_list'

  
end

app/views/partials/_inventory_form.html.erb
<h1>Add Food to Inventory</h1>

<%= form_for @inventory do |f| %>
  <div>
    <%= f.label :food_id, "Select Food" %>
    <%= f.collection_select :food_id, Food.all, :id, :name %>
  </div>
  <div>
    <%= f.label :unit, "Unit" %>
    <%= f.number_field :quantity %>
  </div>
  <div>
    <%= f.label :quantity, "Quantity" %>
    <%= f.number_field :quantity %>
  </div>
  <%= f.submit "Add to Inventory" %>
<% end %>

app/views/partials/_table_food_item.html.erb
<tr>
  <td><%= food.name %></td>
  <td><%= food.measurement_unit %></td>
  <td><%= food.price %></td>
  <td><%= food.quantity %></td>
  <td>
    <%= button_to 'Delete', food_path(food), method: :delete, data: { confirm: 'Are you sure you want to delete this food?' }, class: 'btn-inline danger-text', remote: true %>
  </td>
</tr>

app/views/partials/_table_general_shopping_list.html.erb
<tr>
	<td><%= ingredient.name %></td>
	<td><%= "#{ingredient.total_food} #{get_measurement_prefix(ingredient.measurement_unit)}" %></td>
	<td><%= "$#{ingredient.general_price}" %></td>
</tr>

app/views/partials/_table_recipe_foods_item.html.erb
<tr>
  <td><%= recipe_food.food.name %></td>
  <td><%= "#{recipe_food.quantity}#{get_measurement_prefix(recipe_food.food.measurement_unit)}" %></td>
  <td><%= "$#{recipe_food.total_price}" %></td>
  <td>
    <div class="container_col-2">
      <a href="#" class="inline-button info">Modify</a>
      <%= button_to 'Remove', recipe_recipe_food_path(recipe_food.recipe, recipe_food), method: :delete, remote: true, class: 'inline-button danger' %>
    </div>
  </td>
</tr>