config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'recipes#index'


  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new', as: 'new_food'
  resources :foods, only: [:create,:destroy]

  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    patch 'update_status', on: :member
    resources :food_recipes, only: [:new, :create, :edit, :update, :destroy]
  end
  
  
  get '/public', to: 'recipes#new'
  resources :inventories, only: [:index, :show, :new, :edit,  :update, :create, :destroy]

  # Route for the 'General shopping list' page handled by FoodRecipesController
  get '/general_shopping_list', to: 'general_shopping_list#shopping_list', as: 'general_shopping_list'

  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= yield :stylesheets %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top justify-content-center">
      <a class="navbar-brand text-success" href="#">Recipe App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <%= link_to 'Add New Recipe', new_recipe_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Recipes', recipes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Foods', foods_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Inventories', inventories_path, class: "nav-link" %>
          </li>
        </ul>
        <% if user_signed_in? %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-secondary btn-sm" %>
            </li>
          </ul>
        <% else %>
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <%= link_to 'Sign In', new_user_session_path, class: "btn btn-primary btn-sm" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-secondary btn-sm" %>
            </li>
          </ul>
        <% end %>
      </div>
    </nav>

    <div class="container" style="margin-top: 80px;">
      <!-- Add margin-top to adjust content position -->
      <%= yield %>
    </div>
  </body>
</html>